image: bitnami/git

verify:
  stage: .pre
  script:
    - apt-get update && apt-get install --yes gpg curl
    - mkdir -p "/tmp/gnupg"
    - curl https://git.tu-berlin.de/jcm3.gpg | gpg --import --homedir "/tmp/gnupg"
    - gpgv  --homedir "/tmp/gnupg" --keyring "/tmp/gnupg/pubring.kbx" .gitlab-ci/hashes.txt
    - sha512sum --check .gitlab-ci/hashes.txt
    - comm -23 <(sha512sum Blatt*/praxis/Aufgabe*/Makefile | sort) <(sort .gitlab-ci/hashes.txt) | test $(wc -l) -eq 0

generate-config:
  stage: build
  script: .gitlab-ci/generate-ci-configs.sh > generated-config.yml
  artifacts:
    paths:
      - generated-config.yml

child-pipeline:
  stage: test
  trigger:
    include:
      - artifact: generated-config.yml
        job: generate-config
    strategy: depend
